// Learn cc.Class:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/class.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/class.html
// Learn Attribute:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/reference/attributes.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/reference/attributes.html
// Learn life-cycle callbacks:
//  - [Chinese] http://docs.cocos.com/creator/manual/zh/scripting/life-cycle-callbacks.html
//  - [English] http://www.cocos2d-x.org/docs/creator/en/scripting/life-cycle-callbacks.html

cc.Class({
    extends: cc.Component,

    properties: {
        // foo: {
        //     // ATTRIBUTES:
        //     default: null,        // The default value will be used only when the component attaching
        //                           // to a node for the first time
        //     type: cc.SpriteFrame, // optional, default is typeof default
        //     serializable: true,   // optional, default is true
        // },
        // bar: {
        //     get () {
        //         return this._bar;
        //     },
        //     set (value) {
        //         this._bar = value;
        //     }
        // },
    },

    // LIFE-CYCLE CALLBACKS:

    // onLoad () {},

    start () {
           this.left =  UtilsNode.getNode("left",this.node)
           this.mid =  UtilsNode.getNode("mid",this.node)
           this.right =  UtilsNode.getNode("right",this.node)

           this.left_miss =  UtilsNode.getNode("left_miss",this.node)
           this.right_miss =  UtilsNode.getNode("right_miss",this.node)

        UtilsNode.setOn(this.left,function () {
            let data = {
                der: 1,
                pianyi: 50,
                power:  UtilsNode.getRandom(2,20,30),
                ballSpeed: 20,
                kitTime: 20,
                ATime: 20
            }
            strike.addStrikeAll(data)

            player.playLeft(data)

        }.bind(this))
        UtilsNode.setOn(this.mid,function () {
            let data = {
                der: 2,
                pianyi: 50,
                power: UtilsNode.getRandom(2,70,100),
                ballSpeed: 20,
                kitTime: 20,
                ATime: 20
            }
            strike.addStrikeAll(data)
            player.playMid(data)
        }.bind(this))
        UtilsNode.setOn(this.right,function () {
            let data = {
                der: 3,
                pianyi: 50,
                power: UtilsNode.getRandom(2,20,30),
                ballSpeed: 20,
                kitTime: 20,
                ATime: 20
            }
            strike.addStrikeAll(data)
            player.playRight(data)
        }.bind(this))

        UtilsNode.setOn(this.left_miss,function () {
            let data = {
                der: 3,
                pianyi: 50,
                power: UtilsNode.getRandom(2,31,50),
                ballSpeed: 20,
                kitTime: 20,
                ATime: 20
            }
            strike.addStrikeAll(data)
            player.playLeft(data)
            // player.strike_leftMiss(data)
        }.bind(this))
        UtilsNode.setOn(this.right_miss,function () {
            let data = {
                der: 3,
                pianyi: 50,
                power: UtilsNode.getRandom(2,31,50),
                ballSpeed: 20,
                kitTime: 20,
                ATime: 20
            }
            strike.addStrikeAll(data)
            player.playRight(data)
        }.bind(this))
    },

    // update (dt) {},
});
